export const propertiesData = [
  {
    _id: '1',
    title: 'Luxury Villa',
    description: 'A beautiful luxury villa in the suburbs.',
    price: 1000000,
    location: 'Los Angeles',
    bedrooms: 4,
    bathrooms: 3,
    image:"",
    owner: 'owner1@example.com',
    interestedClients: [], // Empty array for interested clients
  },
  {
    _id: '2',
    title: 'Spacious Apartment',
    description: 'A high-rise apartment in the heart of Mumbai.',
    price: 750000,
    location: 'Mumbai, Maharashtra',
    bedrooms: 3,
    bathrooms: 2,
    owner: 'owner2@example.com',
    image:"",
    interestedClients: ['client1@example.com', 'client2@example.com'],
  },
  {
    _id: '3',
    title: 'Cozy Family House',
    description: 'A small family house in a quiet neighborhood.',
    price: 500000,
    location: 'Pune, Maharashtra',
    bedrooms: 3,
    bathrooms: 2,
    owner: 'owner3@example.com',
    image:"",
    interestedClients: ['client3@example.com'],
  },
  {
    _id: '4',
    title: 'Modern Duplex',
    description: 'A modern duplex located in Navi Mumbai.',
    price: 1200000,
    location: 'Navi Mumbai, Maharashtra',
    bedrooms: 5,
    bathrooms: 4,
    owner: 'owner4@example.com',
    image:"",
    interestedClients: ['client4@example.com', 'client5@example.com'],
  },
  {
    _id: '5',
    title: 'Affordable Studio Apartment',
    description: 'A budget-friendly studio apartment in Thane.',
    price: 300000,
    location: 'Thane, Maharashtra',
    bedrooms: 1,
    bathrooms: 1,
    owner: 'owner5@example.com',
    image:"",
    interestedClients: ['client6@example.com'],
  },
  {
    _id: '6',
    title: 'Beachfront Villa',
    description: 'A beautiful villa with a stunning view of the sea.',
    price: 2000000,
    location: 'Alibaug, Maharashtra',
    bedrooms: 4,
    bathrooms: 3,
    owner: 'owner6@example.com',
    image:"",
    interestedClients: ['client7@example.com', 'client8@example.com'],
  },
  {
    _id: '7',
    title: 'Luxury Penthouse',
    description: 'A luxurious penthouse in the heart of Pune.',
    price: 1800000,
    location: 'Pune, Maharashtra',
    bedrooms: 4,
    bathrooms: 3,
    owner: 'owner7@example.com',
    image:"",
    interestedClients: ['client9@example.com', 'client10@example.com'],
  },
  {
    _id: '8',
    title: 'Countryside Farmhouse',
    description: 'A peaceful farmhouse located near Nashik.',
    price: 950000,
    location: 'Nashik, Maharashtra',
    bedrooms: 3,
    bathrooms: 2,
    owner: 'owner8@example.com',
    image:"",
    interestedClients: ['client11@example.com', 'client12@example.com'],
  },
  {
    _id: '9',
    title: 'Penthouse with City View',
    description: 'A modern penthouse overlooking the city.',
    price: 1500000,
    location: 'Mumbai, Maharashtra',
    bedrooms: 4,
    bathrooms: 3,
    owner: 'owner9@example.com',
    image:"",
    interestedClients: ['client13@example.com'],
  },
  {
    _id: '10',
    title: 'Modern Bungalow',
    description: 'A modern bungalow situated in Lonavala.',
    price: 1350000,
    location: 'Lonavala, Maharashtra',
    bedrooms: 5,
    bathrooms: 4,
    owner: 'owner10@example.com',
    image:"",
    interestedClients: ['client14@example.com', 'client15@example.com'],
  },
];
